TOKENIZERS_PARALLELISM=false MUJOCO_GL=egl PYOPENGL_PLATFORM=egl lerobot-train \
  --policy.path=/home/nipeihuan/models/smolvla_libero \
  --policy.push_to_hub=false \
  --policy.load_vlm_weights=true \
  --policy.enable_partial_update=false \
  --dataset.repo_id=HuggingFaceVLA/libero \
  --env.type=libero \
  --env.task=libero_10 \
  --output_dir=./outputs/train/10_finetune \
  --wandb.enable=false \
  --steps=100000 \
  --batch_size=64 \
  --eval.batch_size=1 \
  --eval.n_episodes=100 \
  --eval_freq=200000